name: good_times
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  get_storage: ^2.1.1
  share_plus: ^7.2.2
  onesignal_flutter: ^5.1.0
  web_socket_channel: ^2.4.0
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.2.1
  flutter_branch_sdk: ^7.1.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.25.4
  # firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  # sign_in_with_apple: ^5.0.0
  dio: ^5.4.0
  get: ^4.6.6
  geolocator: ^10.1.1
  intl: ^0.19.0
  # location: ^5.0.3
  flutter_html: ^3.0.0-beta.2
  flutter_google_places_hoc081098: ^2.0.0-beta.1
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.3
  webview_flutter: ^4.7.0
  # skeletons: ^0.0.3

  syncfusion_flutter_calendar: ^25.1.35
  # syncfusion_flutter_core: ^25.1.35
  path_provider: ^2.1.2
  logger: ^2.1.0
  url_launcher: ^6.2.6
  textfield_tags: ^3.0.1
  package_info_plus: ^4.2.0
  firebase_crashlytics: ^3.5.1
  change_app_package_name: ^1.1.0
  geocoding: ^3.0.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0
  dio_smart_retry: ^6.0.0
  android_play_install_referrer: ^0.4.0
  async: ^2.11.0
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  easy_debounce: ^2.0.3
  flutter_skeleton_ui: ^0.0.6
  statsfl: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  appinio_social_share: ^0.3.2
  fluttertoast: ^8.0.9
  device_apps: ^2.2.0
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/images/logo.jpg"
  android: true
  ios: true

flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"
  image: assets/images/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/lottie/
    - assets/images/feedback/
    - assets/svg/
    - assets/images/event/
    - assets/images/setting/
    - assets/images/bottom_navigation/selected/
    - assets/images/bottom_navigation/unselected/
    - assets/images/logo.png
    - assets/images/intro_slider/
    - assets/images/preferences_icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
