// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-hF6pPqcNYAkEYptxYCr5yPrAakJV2q4',
    appId: '1:132465013831:android:5cda0de1e6aac2fb91ad62',
    messagingSenderId: '132465013831',
    projectId: 'goodtimes-414811',
    storageBucket: 'goodtimes-414811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSaM17_r9xXtPExrDl4NWsqbEBnOVaqI',
    appId: '1:132465013831:ios:730f8177e8fc663e91ad62',
    messagingSenderId: '132465013831',
    projectId: 'goodtimes-414811',
    storageBucket: 'goodtimes-414811.appspot.com',
    androidClientId: '132465013831-6mmesm7valr9ro3fnq20d3no1c53svj2.apps.googleusercontent.com',
    iosClientId: '132465013831-gg9not5n0b16e74uvtmb1eml8rp5i2pe.apps.googleusercontent.com',
    iosBundleId: 'com.app.goodTimes.OneSignalNotificationServiceExtension',
  );
}
